// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enkyfkzheucvauvtomto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVua3lma3poZXVjdmF1dnRvbXRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMzQ4MTYsImV4cCI6MjA1NjkxMDgxNn0.QhZvbj7facKbESM8dy3ShHf4mT2dMoYxOZBBlZ5Ve8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);